name: Pull Request Action
on:
  push:
    branches:
      - dev/*

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      steps
    - name: create pull request
      run: gh pr create -B dev -H main --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
